### ISSUE TITLE
参数及类型错误，无法编译 (AEGHB-897)

### ISSUE THREAD

**Issue by haolsh** [espressif/esp-video-components#12]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

![1732969852869](https://github.com/user-attachments/assets/4cb06bab-59bd-491b-b0e9-e480cfc8158c)

![1732969840545](https://github.com/user-attachments/assets/ce322a6b-d76b-4ba3-9ff0-a5ea7dceb7f8)

### Actual behavior (suspected bug)

master分支

### Steps to reproduce the behavior

esp-video-component 中的esp_video  以及esp_ipa 函数参数错误

### Project release version

espidf-5.4.0

### System architecture

Intel/AMD 64-bit (modern PC, older Mac)

### Operating system

Linux

### Operating system version

ubuntu22.04

### Shell

ZSH

**Comment by wujiangang** [comment]
@WangYuxin-esp Please check about this.

**Comment by donghengqaz** [comment]
Hi @haolsh, thanks for your feedback, this compiling error is fixed in commit https://github.com/espressif/esp-video-components/commit/b5fd2933327118f739cf1e0f0ec2c4f82d08f887, PTAL, or you can also try the master branch.

**Comment by wujiangang** [comment]
It is generally recommended to use the version available on the [ESP-Registry](https://components.espressif.com/). However, using the latest version and reporting any issues is also appreciated.
