### ISSUE TITLE
Support for Sony IMX219 and IMX708 sensors (AEGHB-882)

### ISSUE THREAD

**Issue by mutatrum** [espressif/esp-video-components#9]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Described the feature in detail and justified the reason for the request.
- [X] Provided specific use cases and examples.

### Feature description

Sensors used in the Raspberry Pi Camera Module 2 and 3.

### Use cases

The Raspberry Pi Camera Module v1 works, but is already fairly old. Supporting newer models with higher image quality would be good.

**Comment by WangYuxin-esp** [comment]
Supporting these sensors will require technical support from IMX. There are currently no further plans to debug them together with IMX. Suggest experiencing the currently supported sensors first.
